language: swift
os: osx
osx_image: xcode10.1
xcode_project: Flokk.xcworkspace
xcode_scheme: FlokkTests
podfile: Podfile

before_install:
  - gem install cocoapods
script:
  - set -o pipefail
    - xcodebuild clean build -sdk iphonesimulator -workspace Flokk.xcworkspace -scheme Flokk CODE_SIGNING_REQUIRED=NO
