language: objective-c
os: osx
osx_image: xcode10.1
xcode_project: Flokk.xcworkspace
xcode_destination: platform=iOS Simulator, iOS = 11.0, name=iPhone X
podfile: Podfile

before_install:
  - gem install cocoapods

install:
  - bundle install
  - pod repo update
  - pod install

script:
#  From recommended template from CocoaPods GitHub
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/${POD_NAME}.xcworkspace -scheme ${POD_NAME}-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
    
  - fastlane scan FlokkTests
