language: swift
os: osx
osx_image: xcode10.1
xcode_project: Flokk.xcworkspace
xcode_scheme: FlokkTests
podfile: Podfile

before_install:
  - gem install cocoapods
  - gem install fastlane

script:
  - fastlane scan FlokkTests
