language: swift
os: osx
osx_image: xcode10.1
xcode_project: Flokk.xcworkspace
podfile: Podfile

before_install:
  - gem install cocoapods
  - gem install fastlane

install
  - pod install

script:
  - fastlane scan FlokkTests
