language: swift
os: osx
osx_image: xcode10.1
xcode_project: Flokk.xcworkspace
xcode_scheme: FlokkTests
podfile: Podfile

before_install:
  - gem install cocoapods
  - gem install fastlane --no-ri --nordoc --no-document
install
  -
jobs:
    include:
        - stage: XCTTest
          script:
            - fastlane scan -s FlokkTests

